import Head from "next/head";

const Home: React.FC = () => {
  return (
    <div>
      <Head>
        <title>Vendas app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Bem vindo!
    </div>
  );
};

export default Home;
